### ISSUE TITLE
Roadmap for v3

### ISSUE THREAD

**Issue by jdacosta** [wide/forge#17]
- [ ] Fix this issue : #3 
- [ ] Using the sass-embedded library : https://www.npmjs.com/package/sass-embedded
- [ ] View write logs instantly
- [ ] Replace Parcel by the Eslint library
- [ ]  Find a solution to the fact that Browsersync reloads on every write. Potentially, we have to wait for a group of writes before a page reload.
- [ ] Update all dependencies
- [ ] Make sure you compile with the latest version of node (Node 14 minimum required)
- [ ] Delete the Faker library

**Comment by jdacosta** [comment]
`sass-embedded` is available with forge `3.0.0-alpha.1`
